# 静态链接 MSVC CRT，使 exe 不再依赖 vcruntime140.dll 等 VC++ 运行库，
# 目标机器无需安装 Visual C++ Redistributable 即可运行。
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
